### ISSUE TITLE
App does not recognise type: webview

### ISSUE THREAD

**Issue by jornane** [geteduroam/mobile-app#101]
A profile with `type: webview` does not have an `eapconfig_endpoint`. The app must simply open a web view with the provided `webview_endpoint`. Currently the app displays an error:

> **Cannot complete request**
> Selected profile is missing EAP endpoint.

**Comment by dzolnai** [comment]
Do you have an example organisation for this?

**Comment by jornane** [comment]
For example "The University of Akureyri", there's a lot more if you search in the discovery JSON;

    curl --compressed http://discovery.eduroam.app/v2/discovery.json | json_pp | fgrep webview_endpoint | sort | uniq

**Comment by jornane** [comment]
In any case, the app must verify the `type` field before it tries to read the other fields. We might add other types later.
