### ISSUE TITLE
Geteduroam not working on Android 10

### ISSUE THREAD

**Issue by oheil** [geteduroam/mobile-app#103]
On an Android 10 device:
1) removing all eduroam networks and deinstalling Geteduroam and Eduroam Cat
2) Installing Geteduroam from Google Play
3) Searching Institution (DKFZ) and enter user information, push Install
4) Receiving silent message and push "yes"
5) Connect with WLAN eduroam => enter user and password, a certificate must be selected, we choose the one with EDUROAM in the name.

Now trying to connect to WLAN eduroam does not succeed without any information or error. It just doesn't connect successfully. 

What can we try next? Are there any diagnostics possible to report?

**Comment by pauldekkers** [comment]
Double issue
