### ISSUE TITLE
Version 2.0(678) crash

### ISSUE THREAD

**Issue by Paupaulpistache** [geteduroam/mobile-app#73]
Latest version systematically crashes on my Redmi note 9s MIUI 12.5.1 Android 11
Current stable version I use is 1.0.16

**Comment by dzolnai** [comment]
Hello, thanks for taking the time to submit an issue.
I did not see a recent crash in our crash reporting tool with the device you mentioned, so I am unable to pinpoint the specific cause. If you could make the app crash again, and then [submit a bug report](https://developer.android.com/studio/debug/bug-report#bugreportdevice) to the following email address, I can take a look: daniel [at] egeniq [dot] com

**Comment by pauldekkers** [comment]
This should be resolved in newer versions, no followup on github
