### ISSUE TITLE
Allow importing eap-config files manually

### ISSUE THREAD

**Issue by p-fruck** [geteduroam/mobile-app#74]
The ionic app used to allow users to import eap-configs manually. Is this feature also planned for this version of the app? Currently the app simply displays the start screen when importing such a file.

#56 seems to enable such behavior, however the latest version available on google play does not provide this functionality

**Comment by p-fruck** [comment]
Thanks for the quick reply!
I got the file from a self-hosted CAT instance, therefore the organization is also not part of the `https://discovery.eduroam.app/v1/discovery.json`.
[selfnet.eap-config.txt](https://github.com/geteduroam/mobile-app/files/14126258/selfnet.eap-config.txt)

**Comment by dzolnai** [comment]
That itself should not be an issue. Thanks for the example, I'll give it a try.

**Comment by dzolnai** [comment]
I have found the cause and opened a PR for it. The fix should go live with the next release.

**Comment by SteveBinary** [comment]
For anyone stumbling across this issue: Apparently, the feature to import an `.eap-config` file manually got implemented in #84. See #116
