### ISSUE TITLE
Force closing after entering credentials 

### ISSUE THREAD

**Issue by android-smiley** [geteduroam/mobile-app#76]
Hi,

Unfortunately, after choosing my institution and entering my credentials, the app force closes. I have not found any workaround.

Please see the log below. Let me know, if you need more verbose logs regarding this crash. 

[Error in geteduroam 32025f61e34b.txt](https://github.com/geteduroam/mobile-app/files/14132295/Error.in.geteduroam.32025f61e34b.txt)

```
Device: Google Pixel 7 Pro
OS: Android 14, GrapheneOS, UQ1A.240105.004.2024012600
```

**Comment by dzolnai** [comment]
Thanks for your report with the stack trace. There was an edge case on some institutions that made the validity check on the framework fail. I have opened a PR with the fix.

**Comment by dzolnai** [comment]
I'll close this, feel free reopen if you still see the issue in the next release
